[package]
name = "deval-serde"
version = "0.1.0"
edition = "2024"

[dependencies]
deval-data-model = { version = "0.1.0", path = "../deval-data-model" }
serde = { version = "1.0.219", features = ["derive"] }