[package]
name = "deval-format-json"
version = "0.1.0"
edition = "2024"

[dependencies]
deval-data-model = { version = "0.1.0", path = "../deval-data-model" }
tree-sitter = "0.20"
tree-sitter-json = "0.20"
